# Generated by Django 3.1.1 on 2020-10-06 04:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='College',
            fields=[
                ('short_name', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('long_name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('email', models.EmailField(max_length=100)),
                ('csv', models.FileField(upload_to='csv')),
                ('results', models.FileField(blank=True, null=True, upload_to='csv')),
                ('stamp', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='QuestPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quests', models.IntegerField()),
                ('position', models.IntegerField()),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranklist.college')),
            ],
        ),
        migrations.CreateModel(
            name='LabsPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('labs', models.IntegerField()),
                ('position', models.IntegerField()),
                ('col', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranklist.college')),
            ],
        ),
    ]
