# Generated by Django 3.1.1 on 2020-10-05 09:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ranklist', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QuestPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('quests', models.IntegerField()),
                ('position', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranklist.college')),
            ],
        ),
        migrations.CreateModel(
            name='LabsPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('labs', models.IntegerField()),
                ('position', models.IntegerField()),
                ('college', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ranklist.college')),
            ],
        ),
    ]
