# Generated by Django 3.1.1 on 2020-10-09 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranklist', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position',
            field=models.IntegerField(default=1000),
        ),
    ]
