# Generated by Django 3.1.1 on 2020-10-05 12:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranklist', '0003_college_results'),
    ]

    operations = [
        migrations.AddField(
            model_name='college',
            name='stamp',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now, null=True),
        ),
    ]
