# Generated by Django 3.1.1 on 2020-10-14 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ranklist', '0003_student_stamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='position_labs',
            field=models.IntegerField(default=1000),
        ),
    ]
